<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProveedoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $proveedores = [
            ['nombre' => 'ANA GABRIELA PENA OLVERA'],
            ['nombre' => 'MAYRA MARICELA RAMIREZ COTA'],
            ['nombre' => 'HAIREN JAVIER AGUILAR HERNANDEZ'],
            ['nombre' => 'PABLO CASTILLO CONDE'],
            ['nombre' => 'EDGARD JONATHAS TORRES CALLEJA'],
            ['nombre' => 'SYNDI TRUJILLO BAHENA'],
            ['nombre' => 'JUAN MENDOZA'],
            ['nombre' => 'FABIOLA PACHECO'],
            ['nombre' => 'BLANCA ESTELA PEREZ GARCIA'],
            ['nombre' => 'ERICKA FABIOLA URIBE RAMIREZ'],
            ['nombre' => 'SALOMON CABELLO'],
            ['nombre' => 'ALEJANDRO ANTONIO GUTIERREZ PEREZ'],
            ['nombre' => 'ACTOBELI RAMOS RAMOS'],
            ['nombre' => 'CLAUDIA ARRIAGA CHAPARRO'],
            ['nombre' => 'ANA LIDIA RAMIREZ SEGURA'],
            ['nombre' => 'BIOTONER'],
            ['nombre' => 'GONZALO CERON RIVERA'],
            ['nombre' => 'OSKAR GIOVANNI LOPEZ ESPINOZA'],
            ['nombre' => 'VENTA MOSTRADOR'],
            ['nombre' => 'KILICHIPS'],
            ['nombre' => 'ARGO MATERIALES SA DE CV'],
            ['nombre' => 'MAQUINARIA Y MATERIALES GABY'],
            ['nombre' => 'LIDIA ERENDY SOLIS HERNANDEZ'],
            ['nombre' => 'RICARDO NAJAR'],
            ['nombre' => 'TABIQUE AGUSTIN'],
            ['nombre' => 'DIMEO'],
            ['nombre' => 'YEZBEK'],
            ['nombre' => 'BORDADOS RIYANEL'],
            ['nombre' => 'TELMEX'],
            ['nombre' => 'MAILBOXES'],
            ['nombre' => 'MADERERIA VARGAS'],
            ['nombre' => 'ANDRES SAN JUAN'],
            ['nombre' => 'ELECTRICA JIBE SA DE CV'],
            ['nombre' => 'ESPERANZA CHAVEZ'],
            ['nombre' => 'CEMENTOS DEL BAJIO'],
            ['nombre' => 'GABRIELA ENRIQUEZ MARTINEZ'],
            ['nombre' => 'ISRAEL TORIBIO BARCENAS'],
            ['nombre' => 'IVETTE AGUILAR HERNANDEZ'],
            ['nombre' => 'MADERERIA VARGAS'],
            ['nombre' => 'INSTITUTO MEXICANO DEL SEGURO SOCIAL'],
            ['nombre' => 'CAPIPRINT COLORMAKE'],
            ['nombre' => 'CUBO CONCRETOS'],
            ['nombre' => 'MERCAPISOS'],
            ['nombre' => 'SECUNDINO LOPEZ'],
            ['nombre' => 'EVELINA BAHENA'],
            ['nombre' => 'VISTA REAL COUNTRY CLUB'],
            ['nombre' => 'ALEJANDRO VERA'],
            ['nombre' => 'JAVIER MACIAS'],
            ['nombre' => 'COLEGIO DE ARQUITECTOS DEL ESTADO DE QUERETARO CAEQ'],
            ['nombre' => 'OFFICE DEPOT'],
            ['nombre' => 'HOME DEPOT'],
            ['nombre' => 'SDI'],
            ['nombre' => 'YAZBEK'],
            ['nombre' => 'PEDRO DIAZ'],
            ['nombre' => 'IMPULSO EMPRESARIAL'],
            ['nombre' => 'GUILLERMO ANTONIO RAMIREZ COTA'],
            ['nombre' => 'DANIEL LOZANO DE PAZ'],
            ['nombre' => 'ANA LETICIA LIZARRAGA MARTINEZ'],
            ['nombre' => 'DANIEL BENITEZ GARCIA'],
            ['nombre' => 'ANTONIO CEDILLO'],
            ['nombre' => 'SAYURI RAMIREZ VILLANUEVA'],
            ['nombre' => 'ALEJANDRO GUTIERREZ REGUERA'],
            ['nombre' => 'EDUARDO BACHA TOLEDO'],
            ['nombre' => 'ODIN JOSHUA ALAMILLA GATICA'],
            ['nombre' => 'SERGIO GONZALEZ BRAVO'],
            ['nombre' => 'DISTRIBUCION INTERCERAMIC SA DE CV'],
            ['nombre' => 'RODOLFO CORREA CAMPUZANO'],
            ['nombre' => 'PISOS Y MAS DE QUERETARO SA DE CV'],
            ['nombre' => 'MA ENEDINA VICTORIA'],
            ['nombre' => 'JOSE LINARES PICHARDO'],
            ['nombre' => 'CONCRETOS PROFESIONALES DE QUERETARO'],
            ['nombre' => 'ANTONIO MARTINEZ RESENDIZ'],
            ['nombre' => 'JUAN ANTONIO ROSAS'],
            ['nombre' => 'MADERERIA MONTE VERDE'],
            ['nombre' => 'DEMETRIO PEREZ ALVAREZ'],
            ['nombre' => 'PEDRO VARGAS'],
            ['nombre' => 'AMADO VARGAS'],
            ['nombre' => 'ARAA MATERIALES'],
            ['nombre' => 'JUANA ERIKA ROBLES ACOSTA'],
            ['nombre' => 'FERNANDO VICTOR HIDALGO TOVAR'],
            ['nombre' => 'ASYHS PIPAS'],
            ['nombre' => 'LA CASA DEL PLOMERO'],
            ['nombre' => 'Diana Aylin Mendoza'],
            ['nombre' => 'MIGUEL ANGEL ARTEAGA ZUMAYA'],
            ['nombre' => 'ALVAC'],
            ['nombre' => 'VM Esqueda tres S de RL de CV'],
            ['nombre' => 'RAUL FLORES'],
            ['nombre' => 'MARIO RESENDIZ'],
            ['nombre' => 'CALIXTO DE SANTIAGO'],
            ['nombre' => 'LAVANDA INMOBILIARIA'],
            ['nombre' => 'ISSA'],
            ['nombre' => 'IVETTE'],
            ['nombre' => 'MARMOLES PUENTE'],
            ['nombre' => 'INSTITUTO MEXICANO DEL SEGURO SOCIAL'],
            ['nombre' => 'ROBERTO JAVIER PEREZ'],
            ['nombre' => 'JOSE JESUS JUAN'],
            ['nombre' => 'FANOSA'],
            ['nombre' => 'UNITAM'],
            ['nombre' => 'ECONOTRANSFER QUERETARO'],
            ['nombre' => 'CENTRAL FERRETERA TREJO'],
            ['nombre' => 'EDGAR JOSUE RIVERA'],
            ['nombre' => 'JULIO DAVID ESCAMILLA MATA'],
            ['nombre' => 'MARIA DOLORES H'],
            ['nombre' => 'IMSS'],
            ['nombre' => 'EMANUEL ANTONIO AVILA GARCIA'],
            ['nombre' => 'DANIELA ESPINOSA'],
            ['nombre' => 'LAMINADOS DE BARRO'],
            ['nombre' => 'FRANCISCO GERVASIO HURTADO'],
            ['nombre' => 'CONSTRU MATERIALES TREJO'],
            ['nombre' => 'PORCELANICOS ALBATROS'],
            ['nombre' => 'GUILLERMO SALMON'],
            ['nombre' => 'NOE LOPEZ GUERRERO'],
            ['nombre' => 'LA CASA DEL TAPIZ'],
            ['nombre' => 'GERSA'],
            ['nombre' => 'URIEL JASSO'],
            ['nombre' => 'AMAZON'],
            ['nombre' => 'IMA SERVICIOS'],
            ['nombre' => 'JOSE DE JESUS ARIAS GARCIA'],
            ['nombre' => 'GRUPO SIM'],
            ['nombre' => 'JOSE MIGUEL MEDINA PACHECO'],
            ['nombre' => 'JOSE LUIS PEREZ ROCHA'],
            ['nombre' => 'AZULEJOS Y PISOS ARTESANALES'],
            ['nombre' => 'PORCELANOSA'],
            ['nombre' => 'CANTERA Y BARRO'],
            ['nombre' => 'J Dolores Martines Perez'],
            ['nombre' => 'AZULEMEX'],
            ['nombre' => 'MADERERIA LOMAS DE LA HACIENDA'],
            ['nombre' => 'JOSE JESUS J CHAVEZ'],
            ['nombre' => 'HUGO MORADO ARAMBURO'],
            ['nombre' => 'GUADALUPE WAUMAN'],
            ['nombre' => 'MATERIALES EL PIPILA'],
            ['nombre' => 'RAMON'],
            ['nombre' => 'CIRO CHAVEZ UGALDE'],
            ['nombre' => 'ABRAHAM RESENDIZ'],
            ['nombre' => 'HERRACEQ'],
            ['nombre' => 'PINTURAS EZEQUIEL MONTES DE QRO'],
            ['nombre' => 'ELEMENTOS PREFABRICADOS'],
            ['nombre' => 'VIDRIO Y ALIMINIO LEONS'],
            ['nombre' => 'ELEMENTOS PREFABRICADOS LA CANADA'],
            ['nombre' => 'SALVADOR GONZALEZ BOVADILLA'],
            ['nombre' => 'ANA LAURA ACOSTA'],
            ['nombre' => 'TATSA'],
            ['nombre' => 'ELMEX'],
            ['nombre' => 'BTICINO'],
            ['nombre' => 'TRINIDAD CABRERA'],
            ['nombre' => 'JACQUELINE'],
            ['nombre' => 'JACQUELINE TREJO'],
            ['nombre' => 'MARGARITO GUDIÑO'],
            ['nombre' => 'CUBIMAS'],
            ['nombre' => 'LUIS ALFREDO CANO DAVILA'],
            ['nombre' => 'DANIEL CRUZ'],
            ['nombre' => 'CESAR GUDIÑO'],
            ['nombre' => 'ISUI GM'],
            ['nombre' => 'ERNESTO ROBLEDO'],
            ['nombre' => 'ALDO MOSCOSO'],
            ['nombre' => 'JOSE JUAN ESTRADA'],
            ['nombre' => 'TENSION EN CONCRETO'],
            ['nombre' => 'GUADALUPE RESENDIZ'],
            ['nombre' => 'DIEGO MARTINEZ'],
            ['nombre' => 'SOLUCIONES EMPRESARIALES'],
            ['nombre' => 'MATERIALES PLAZAS DEL SOL'],
            ['nombre' => 'ORLANDO LOPEZ'],
            ['nombre' => 'JOCELYN GALVEZ'],
            ['nombre' => 'IRMA ALEJANDRINA DUVIGNAU'],
            ['nombre' => 'MADERERIA ZARMA'],
            ['nombre' => 'PLOMERIA Y CERAMICA DE QUERETARO'],
            ['nombre' => 'EMMANUEL T'],
            ['nombre' => 'HECTOR GARRIDO TORRES'],
            ['nombre' => 'FRANCISCO JAVIER'],
            ['nombre' => 'ALBERTO'],
            ['nombre' => 'EDUARDO SALCEDO TEYSSIER'],
            ['nombre' => 'JUAN GERARDO LORANCA'],
            ['nombre' => 'COMEX'],
            ['nombre' => 'VIBROMAQ'],
            ['nombre' => 'DANIEL MELENDEZ'],
            ['nombre' => 'EDMUNDO JIMENEZ'],
            ['nombre' => 'MALLA ARQ'],
            ['nombre' => 'JOSE RICARDO'],
            ['nombre' => 'CONCRETERA QUERETANA'],
            ['nombre' => 'ABRAHAM ORTEGA'],
            ['nombre' => 'IGNACIO BEERRA TREVINO'],
            ['nombre' => 'PISOS DE MADERA ALCA'],
            ['nombre' => 'RAUL EMMANUEL GUZMAN'],
            ['nombre' => 'IGNACIO BEERRA TREVINO'],
            ['nombre' => 'HUMBERTO ROMERO PINEDA'],
            ['nombre' => 'RICARDO VALENCIA'],
            ['nombre' => 'PINTURAS DOAL'],
            ['nombre' => 'RAFAEL J OSUNA'],
            ['nombre' => 'LILIA MONTAÑO'],
            ['nombre' => 'ALFREDO M'],
            ['nombre' => 'SUPERFICIES LIMPIAS DE QUERETARO'],
            ['nombre' => 'ANTONIO SANDOVAL'],
            ['nombre' => 'CLIMQRO'],
            ['nombre' => 'ADRIANA MARTINEZ BALTAZAR'],
            ['nombre' => 'FERRETERIA Y ACEROS PRADO'],
            ['nombre' => 'CONCRETOS ARSO'],
            ['nombre' => 'JAVIER SANCHEZ'],
            ['nombre' => 'AGUA CASA BLANCA'],
        ];

        foreach ($proveedores as $proveedor) {
            DB::table('proveedores')->insert([
                'nombre' => $proveedor['nombre'],
                'telefono' => '',
                'email' => '',
                'direccion' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ]);
        }
    }
}
